# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'P2-RPC'

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      - uses: actions/checkout@v4
  
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package -e --file 2_Distributed_System/rpc/pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn -B deploy -e -DskipTests=true --file /home/runner/work/uestc/uestc/2_Distributed_System/rpc/pom.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
